(* ::Package:: *)

If[$MachineName=="julio-mba",
dir="/Users/julio/Desktop/Research/projects/N8SUGRA/vacuums/",
dir="/u/project/bern/bern/fourloop/bcj/math_integrateN8/"];
Get[dir<>"VacuumData5Loops"];
<<IGraphM`;


(* We ignore factorized graphs (i.e., graphs with tadpoles or dangling sunsets) from the beggining *)
Table[contnotadpoles[i]=Select[cont[i],(Not[hasTadpolesQ[#]]&&Not[hasDanglingSunsetQ[#]])&];,{i,0,7}];
Table[Length[contnotadpoles[i]],{i,0,7}]


(* At each levels we remove duplicates by isomorphism and sliding bubbles*)


slid[0]=Union[Fold[Union,slideBubbles/@contnotadpoles[0]],SameTest->isomorphicQuptoBubbles];


slid[1]=Union[Fold[Union,slideBubbles/@contnotadpoles[1]],SameTest->isomorphicQuptoBubbles];


slid[2]=Union[Fold[Union,slideBubbles/@contnotadpoles[2]],SameTest->isomorphicQuptoBubbles];


slid[3]=Union[Fold[Union,slideBubbles/@contnotadpoles[3]],SameTest->isomorphicQuptoBubbles];


slid[4]=Union[Fold[Union,slideBubbles/@contnotadpoles[4]],SameTest->isomorphicQuptoBubbles];


slid[5]=Union[Fold[Union,slideBubbles/@contnotadpoles[5]],SameTest->isomorphicQuptoBubbles];


slid[6]=Union[Fold[Union,slideBubbles/@contnotadpoles[6]],SameTest->isomorphicQuptoBubbles];


(* We merge all the levels and remove duplicates by isomorphism and sliding bubbles*)
isouptobubble=Union[Fold[Union,slid/@Range[0,6]],SameTest->isomorphicQuptoBubbles];


(* We remove extra factorized graphs generated by moving bubbles*)
minbasis=GroupBy[Select[isouptobubble,Not[hasDanglingSunsetQ[#]]&],nEdges];


(* The counting is different from the thesis because there is a top graph and 
several daughters that have a double propagator not coming from bubbles or sunsets *) 
Length/@Reverse@(Values[minbasis])
